name: Sync to Azure DevOps

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches:
      - '**'


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Sync to Azure DevOps
        run: |
          # Set variables
          PAT="${{ secrets.AZURE_DEVOPS_EXT_PAT }}"
          ORG="ofgi"
          PROJECT="Architecture Lab"
          REPO="AvaloniaPoker"
          BRANCH="${{ github.ref_name }}"
          SHA="${{ github.sha }}"

          echo "Branch: $BRANCH"
          echo "SHA: $SHA"

          # URL encode the project name (simpler approach)
          PROJECT_ENC=$(echo "$PROJECT" | sed 's/ /%20/g')

          # API base URL
          API_URL="https://dev.azure.com/$ORG/$PROJECT_ENC/_apis/git/repositories/$REPO"

          echo "API URL: $API_URL"

          # Test PAT with a simple API call
          echo "Testing authentication..."
          AUTH_TEST=$(curl -s -o /dev/null -w "%{http_code}" -u ":$PAT" \
            "https://dev.azure.com/$ORG/_apis/projects?api-version=6.0")

          echo "Auth test HTTP status: $AUTH_TEST"

          if [ "$AUTH_TEST" != "200" ]; then
            echo "Authentication failed! Check your PAT token."
            exit 1
          fi

          # API base URL
          API_URL="https://dev.azure.com/$ORG/$PROJECT_ENC/_apis/git/repositories/$REPO"

          # Authorization header with base64 encoded PAT
          AUTH_HEADER="Authorization: Basic $(echo -n ":$PAT" | base64)"

          # Check if branch exists
          echo "Checking if branch exists..."
          REFS_RESPONSE=$(curl -s -u ":$PAT" \
            "$API_URL/refs?filter=heads/$BRANCH&api-version=6.0")

          # Save HTTP status code
          REFS_STATUS=$?

          echo "Refs API status: $REFS_STATUS"
          echo "Refs API response: $REFS_RESPONSE"

          # If curl failed completely
          if [ $REFS_STATUS -ne 0 ]; then
            echo "Failed to connect to Azure DevOps API. Check your network and API URL."
            exit 1
          fi

          # Try a different API call to test repository access
          echo "Testing repository access..."
          REPO_TEST=$(curl -s -u ":$PAT" \
            "$API_URL?api-version=6.0")

          echo "Repository API response: $REPO_TEST"

          # Try creating/updating branch directly with simplified approach
          echo "Attempting to update branch reference..."

          # Simplified JSON for creating/updating the branch
          REF_JSON="[{\"name\":\"refs/heads/$BRANCH\",\"newObjectId\":\"$SHA\",\"oldObjectId\":\"0000000000000000000000000000000000000000\"}]"

          echo "Reference JSON: $REF_JSON"

          # Add verbose flag to see more details about the request
          UPDATE_RESPONSE=$(curl -v -u ":$PAT" \
            -H "Content-Type: application/json" \
            -d "$REF_JSON" \
            "$API_URL/refs?api-version=6.0")

          echo "Update response: $UPDATE_RESPONSE"
