name: Sync to Azure DevOps

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches:
      - '**'


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create branch in ADO if it doesn't exist
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -x
            az devops configure --defaults organization=https://dev.azure.com/ofgi project="Architecture Lab"
            pat="${{ secrets.AZURE_DEVOPS_EXT_PAT }}"
            echo $pat | az devops login
            branchName="${{ github.ref_name }}"
            branchExists="$(az repos ref list -r AvaloniaPoker --filter heads/$branchName | grep $branchName)"
            if [ -z $branchExists ]; then
              echo -n "Branch $branchName does not exist, creating it..."
              objectId="$(az repos ref list -r AvaloniaPoker --filter heads/main | jq -r '.[] | .objectId')"
              if [ -z $objectId]; then
                echo "No main branch found!"
                exit 1
              fi
              az repos ref create --name "heads/$branchName" -r AvaloniaPoker --object-id $objectId
              echo "created"
            fi

      - name: Add Azure DevOps remote
        run: |
          git remote add azure "https://${{ secrets.AZURE_DEVOPS_EXT_PAT }}@dev.azure.com/ofgi/Architecture%20Lab/_git/AvaloniaPoker"
          git fetch azure

      - name: Push changes to Azure DevOps
        run: |
          git push azure $branchName || echo "Git push failed"
