name: Sync to Azure DevOps

on:
  push:
    branches:
      - '**'


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync to DevOps
        uses: azure/cli@v2
        with:
          inlineScript: |
            az devops configure --defaults organization=https://dev.azure.com/ofgi project="Architecture Lab"
            pat="${{ secrets.AZURE_DEVOPS_EXT_PAT }}"
            echo $pat | az devops login
            branchName="${{ github.ref_name }}"
            branchExists=$(az repos ref list -r AvaloniaPoker --filter heads/$branchName | grep $branchName)
            if ([ -z $branchExists ]); then
              objectId=$(az repos ref list -r AvaloniaPoker --filter heads/main | jq -r '.[] | .objectId')
              if ([ -z $objectId]); then
                echo "No main branch found!"
                exit 1
              fi
              az repos ref create --name "heads/$branchName" -r AvaloniaPoker --object-id $objectId
            fi
            git remote add azure "$pat@https://dev.azure.com/ofgi/Architecture%20Lab/_git/AvaloniaPoker"
            git push azure $branchName
