name: Sync to Azure DevOps

on:
  push:
    branches:
      - '**'


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to DevOps
        uses: azure/cli@v2
        with:
          inlineScript: |
            az devops configure --defaults organization=https://dev.azure.com/ofgi project="Architecture Lab"
            echo "${{ secrets.AZURE_DEVOPS_EXT_PAT }}" | az devops login --organization https://dev.azure.com/ofgi
            branchName="${{ github.ref_name }}"
            branchExists=$(az repos ref list -r AvaloniaPoker --filter heads/$branchName | grep -q $branchName)
            if ([ -z $branchExists ]); then
              $commitId = git rev-parse HEAD
              az repos ref create -r AvaloniaPoker --name "refs/heads/$branchName" --object-id $commitId
            fi
            az repos update -r AvaloniaPoker --default-branch $branchName
