name: Sync to Azure DevOps

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches:
      - '**'


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Sync to Azure DevOps
        run: |
          # Set variables
          PAT="${{ secrets.AZURE_DEVOPS_EXT_PAT }}"
          ORG="ofgi"
          PROJECT="Architecture Lab"
          REPO="AvaloniaPoker"
          BRANCH="${{ github.ref_name }}"
          SHA="${{ github.sha }}"

          echo "Branch: $BRANCH"
          echo "SHA: $SHA"

          # URL encode the project name
          PROJECT_ENC=$(echo "$PROJECT" | sed 's/ /%20/g')

          # Setup Git
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          # Add Azure DevOps as a remote
          git remote add ado "https://$PAT@dev.azure.com/$ORG/$PROJECT_ENC/_git/$REPO"

          # Fetch from Azure DevOps to see what's there
          git fetch ado || true

          # Make sure we have all the current branch's commits
          git fetch --unshallow || true

          echo "Current GitHub branch state:"
          git log -n 3 --oneline

          # Create a new orphan branch with no parents
          echo "Creating clean branch for push..."
          git checkout --orphan temp-branch-clean

          # Add all files from the current state
          git add -A

          # Create a commit with the current state
          git commit -m "Synced state from GitHub $BRANCH branch at $SHA"

          # Force push this clean branch to ADO
          echo "Pushing to Azure DevOps..."
          git push ado "temp-branch-clean:refs/heads/$BRANCH" --force

          echo "Push complete."
