name: Sync to Azure DevOps

on:
  push:
    branches:
      - main


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DevOps
        uses: azure/cli@v2
        env:
          AZURE_DEVOPS_EXT_PATH: ${{ secrets.AZURE_DEVOPS_EXT_PATH }}
        with:
          azcliversion: 2.69.0
          inlineScript: |
            az devops configure --defaults organization=https://dev.azure.com/ofgi project=AvaloniaPoker
            echo $AZURE_DEVOPS_EXT_PATH | az devops login --organization https://dev.azure.com/ofgi --token

      - name: Sync repository to AzureDevOps
        uses: azure/cli@v2
        with:
          inlineScript: |
            az devops configure --defaults organization=https://dev.azure.com/ofgi project=AvaloniaPoker
            az repos import create --git-source-url https://github.com/ofgirichardsonb/AvaloniaPoker --repository AvaloniaPoker --requires-authorization false
