name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: ['8.0.x']

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test MSA.Foundation
      run: dotnet test MSA.Foundation.Tests --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage-results
    
    - name: Test PokerGame
      run: dotnet test PokerGame.Tests --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage-results
    
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    
    - name: Generate Coverage Report
      run: reportgenerator -reports:./coverage-results/**/*.xml -targetdir:./coverage-report -reporttypes:Html
    
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-${{ matrix.os }}
        path: ./coverage-report
        if-no-files-found: error